### ISSUE TITLE
Any idea/indication when v2.14 will be released?

### ISSUE THREAD

**Issue by vraravam** [FasterXML/jackson-datatypes-misc#21]
The changes in 2.14 that have been merged from that branch into the master branch seem really good - for eg, we are looking for the serialization/deserialization changes that were done.

Unfortunately, since this hasnt been released, we ended up cobbling some code (not the best) to make our code work. But, would love if 2.14 can be released soon so that we can remove our wrapper code.

**Comment by cowtowncoder** [comment]
Hi @vraravam! Unfortunately due to bit limited time I have been able to spent on OSS the progress towards 2.14 has been bit limited -- and that new CVE (see databind issue 2816) has taken more focus than ideal. So release is not imminent.

But if all goes well I could see the first Release Candidate going out by early May 2022 and possibly (with somewhat "smaller" release), perhaps final 2.14.0 by early June.

**Comment by vraravam** [comment]
Just bumping this up for visibility. TIA @cowtowncoder

**Comment by cowtowncoder** [comment]
Please use the mailing list for any further communication.

Although I will consider the possibility of using issue tracker for tracking actual release once we get closer -- no immediate plan so final 2.14.0 won't be out before end of May 2022 at least.
